
name: 'infra'
include:
  - cassandra/docker-compose.yml
  - mysql/docker-compose.yml
  - azure-sql-edge/docker-compose.yml
  - postgres/docker-compose.yml

networks:
  tejaswi-net:
    name: tejaswi-net
    driver: bridge